### PR TITLE
Member only mode

### LINKED ISSUE #58: [Feature]: Members only filter
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue for LiveTL.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am not reporting a bug. If I am, I will use the bug report issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Is your feature request related to a problem? Please describe.

see belo

### Describe the solution you'd like

https://youtube.com/clip/UgkxO0kQYBrGi0fGvmKi7PJBuCRBpUmIHvTJ

tldr: only show member messages so kiara doesn't get backseated

### Expected behavior

see belo

### Describe alternatives you've considered

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by r2dev2**
Fixes #58

### CODE REVIEW

**Comment by KentoNishi** [comment]
talked with @r2dev2 in dms, this finna be put together with https://github.com/LiveTL/HyperChat/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by r2dev2** [comment]
@KentoNishi 's code in #56 has been integrated in this PR.

**Comment by KentoNishi** [comment]
## default

image


## when membership filter was enabled, it looked hella weird
image


## i `flex`ed my newfound css skills to get it to align to the bottom when empty
image

**Review by KentoNishi — APPROVED** [review]

**Review by ChrRubin — APPROVED** [review]

**Comment by KentoNishi** [comment]
ayo an immediate pr approval pog

**Comment by KentoNishi** [comment]
2:30am rn so imma work on releasing this tmr

**Pull request merged**
