### PR TITLE
Regex filter chat messages

### PR DESCRIPTION
**Pull request by kortik0**
Created for issue #81.
As described in the task, filtering can take place in two ways - filtering by a certain phrase or word or filtering based on a regular expression. 
You can also specify which criteria will be used for filtering - message or nickname.
Filtering doesn't take emoji into account.

### CODE REVIEW

**Comment by KentoNishi** [comment]
Hmm, I'm a bit on the fence about this. In our discord server, we've been talking about taking over development of the ytcfilter extension and delegating all filtering functionality to that instead. This is a good starting point for that, but I'd like to avoid including it in hyperchat just yet. I'll get back to you on this later

**Comment by kortik0** [comment]
Okay, I don't see the problem.

**Comment by KentoNishi** [comment]
I think u mean "no problem" LOL

anyways, could you maybe join our discord so we can continue this discussion?

https://livetl.app/discord

the plan is, after migrating hyperchat and livetl to mv3, we re-implement all [ytcfilter](https://chrome.google.com/webstore/detail/ytcfilter/mnldnbhgfocmkehnlkeanlhfmopepnko?hl=en-US) by building off of hyperchat. what makes this complicated is that ytcfilter will need to work *without* hyperchat (compatible with default ytc/other ytc extensions). 

it would be AMAZING if you could help us clone ytcfilter functionality in the near future :)

**Comment by kortik0** [comment]
Replying a little late, but still.

About the first remark. I don't think that I need to decide what it should look like. So I decided to just leave an empty space for messages that didn't get filtered. As a working sample, I chose between this option and the option that was listed in the extension in the issue.
About the second one I completely agree, the idea that we should allow users to choose is needed to show only filtered messages came after I posted this PR.
And I would like to know how exactly the settings broke. Before pushing, I checked all the settings, but I'm afraid it does not make any sense anymore.

**Comment by KentoNishi** [comment]
closing for now, but @kortik0 i'll let u know when we start working on ytcfilter so u can help us out :)

**Pull request closed without merging**
