### PR TITLE
kiara bday message

### PR DESCRIPTION
**Pull request by KentoNishi**

### CODE REVIEW

**Review by r2dev2 — APPROVED** [review]
U rlly just made a pr to include ur custom superchat so that u don't have to pay for it

**Comment by KentoNishi** [comment]
look man

u rite ive got no excuses

**Comment by ChrRubin** [comment]
Can I abstain? I'm kinda uncomfortable approving this but its your extension lmao.

**Comment by KentoNishi** [comment]
@ChrRubin ofc u can that's why I asked for a review lmao

In that case I'll scrap the message and replace with an easter egg that turns the welcome message from purple to orange

**Comment by Candygoblen123** [comment]
I may be reading this wrong, but it looks like the message appears regardless of what chat you're looking at. Could you make it only appear if the user is looking at Kiara's chat?

**Comment by KentoNishi** [comment]
Alternatively I can just truncate the message to make it a bit less directed? Idk I need to know what ur comfortable with to decide on what to do

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by ChrRubin** [comment]
I'm with Candy here, a simple "Happy Birthday" or turning the welcome message orange on the exact day would be fine, the full message would be better as a tweet imo.

**Comment by KentoNishi** [comment]
https://user-images.githubusercontent.com/38841491/176972668-13de8715-5765-4062-82cf-1e7cf62255eb.mp4

how dis @ChrRubin

**Review by ChrRubin — APPROVED** [review]

**Pull request merged**
