### PR TITLE
Revert chunk delay

### LINKED ISSUE #34: Delayed messages
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue with LiveTL.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Describe the bug

Apparently, many users are experiencing a thing where all messages are delayed in a live environment. This sounds like an issue of us adding too much of a delay once the chunk is received. Since live chat chunks are so frequent, can we just not add any delay to live messages? We can keep it for archived chats, but for live ones, we can just show messages instantly without worrying about timing,

### Steps To Reproduce

To find users complaining about this, just go to the Hololive fan discord and search "hyperchat."

### Expected behavior

no delay

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Other (Put it in the "Anything else?" section)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ChrRubin**
Reverts my previous change of adding chunk delays to "fix" visual freezes when YT sends message chunks late.

Fixes #34.

### CODE REVIEW

**Review by KentoNishi — APPROVED** [review]
I'll add changelogs tomorrow when I publish this

**Review by r2dev2 — APPROVED** [review]
I feel like there some more freezes with this removed than before in very high activity archived chats. However, it seems to be better for low activity chats and the chat frame itself doesn't go blank as often when scrubbing.

I may just be seeing things because it's 11 PM for me so can someone else (@KentoNishi) check if [suisei sing stream](https://www.youtube.com/watch?v=7xHFtgfHJcA&t=3307s) is worse with this patch or with master?

**Comment by KentoNishi** [comment]
lmfao it only activates on replays and we talked in dms, this is gud to go

**Comment by ChrRubin** [comment]
The chunk delays never get used for archived chats, only for live chats.

**Comment by KentoNishi** [comment]
image

**Comment by ChrRubin** [comment]
Probably should've demonstrated earlier, but this is the visual freezes I'm talking about with chunk delay removed on Pekora's birthday live:

https://user-images.githubusercontent.com/20059164/149141364-d31778b7-22fd-4e8c-8c03-9c9d36a0eb99.mp4

**Comment by ChrRubin** [comment]
I've also been wondering how YTC deals with this, but I guess it doesn't? Seems like the slowness of YTC actually works in its own favour since it takes so long to render messages that you probably can't tell whenever chunks arrive late lmao

https://user-images.githubusercontent.com/20059164/149142647-b3bdbd57-f68c-4d8c-b559-ba4afd16baeb.mp4

**Comment by KentoNishi** [comment]
lmaooooo

**Pull request merged**
