### PR TITLE
HyperChat compat with external scripts/extensions, improve dev build, fix missing author parsing

### PR DESCRIPTION
**Pull request by lbmaian**
Primarily motivated with making the Google Translate extension work with HyperChat, namely being able to access the HyperChat frame contents. Also addressed a couple other things along the way.

1. HyperChat frame now shares same origin as parent frame to avoid cross origin issues. This is done with a combination of `document.write` the iframe's HTML (to make it "inherit" parent frame's location) and inserting `hyperchat.bundle.js` as an extension content script, replacing the usage of `hyperchat.html` as an extension page.
    * Parameters are now passed via iframe element data attributes rather than query parameters
    * Involves the addition of `html-webpack-skip-assets-plugin` to prevent `hyperchat.html` from including the `hyperchat.bundle.js` script import (since it's now injected as an extension content script)
    * Also uses `BannerPlugin` to ensure content scripts are "targeted" to the correct frame since now both the chat frame and HyperChat frame share the same location (due to `document.write`)
    * I tried using `srcdoc` iframe attribute rather than `document.write`, but although it does allow external script access to the frame's contents, it was insufficient for Google Translate for some reason
2. Some development build improvements (`yarn build`)
    * HMR only enabled in watch mode (`yarn start`, `yarn build --watch`)
    * Always tree shake CSS (`purgecss`), even in dev mode, to avoid gigantic CSS files
    * Don't minimize in `manifest.json` and always concatenate output modules in dev mode for easier-to-understand output
3. Fixed parsing missing authorName (yes, this is apparently possible)
    * Also `console.error` failed parse actions (used to identify this bug)

Some of the changes need to be ported to LiveTL as well, namely `webpack.config.json`, `postcss.config.js`, `package.json`

### CODE REVIEW

**Comment by KentoNishi** [comment]
what a madlad

We actually discussed doing this a long time ago but never carried through with it. Amazing that you went ahead and got it working, will review sometime soon

**Comment by ChrRubin** [comment]
HyperChat isn't injecting properly on both watch and production, the iframe body is just blank.:
image

Also, this injection method might cause the [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1231231) mentioned in #16, which I haven't noticed happening since our move to Svelte. While the bug only happened to us randomly during Vue HyperChat, creating an empty iframe and then populating it with Javascript is exactly what they provided as a 100% reproducible example, which is still present in Chromium 96.0.4664.45.

**Comment by lbmaian** [comment]
Huh, I thought I had solved that issue with leaving `run_at` at `document_idle` but looks like it's not reliable. Probably a timing issue with when Chrome decides to try injecting the content script, i.e. matching/injecting before the `document.write`. I don't think that Chromium bug you linked is at fault, since I'm not using `window.stop()`.

I originally tried a `srcdoc` approach and also an `about:blank` with DOM replacement approach, but while HyperChat functioned fine with such approaches, it somehow wasn't sufficient for the Google Translate extension. Seems like that extension doesn't consider `about:blank`/`about:srcdoc` locations as "same origin"?

The only other alternative I can think of is to load the iframe to a dummy youtube URL then replace its contents, but that's not only wasteful and slow, it can also load YT scripts which can't be stopped unless `window.stop()` is used. I think I could use an intentionally invalid YT URL to load the relatively light 404 page, but I'd rather not resort to this.

So that's why I went with the `document.write` approach. I'll tinker some more with it.

**Comment by KentoNishi** [comment]
there's a dummy url we can use: the 404 page. We actually use this trickery in some instances to load the video player, so I'll look into what I can do when I review

In the meantime, could you separate this or into separate parts? ie. Update to dev configuration, injection change, chat parsing fix. I'd like to review and merge them individually

**Comment by ChrRubin** [comment]
Kento please no lmao

**Comment by KentoNishi** [comment]
lmao

**Comment by lbmaian** [comment]
> In the meantime, could you separate this pr into separate parts? ie. Update to dev configuration, injection change, chat parsing fix. I'd like to review and merge them individually

Ok will do.

**Comment by lbmaian** [comment]
Split off #28 and #29

**Comment by lbmaian** [comment]
> HyperChat isn't injecting properly on both watch and production, the iframe body is just blank.:

I couldn't reproduce this on latest Chrome on Windows. I did notice that if I added `run_at=document_end`, it never works, but if I then add `match_about_blank=true`, it works again, indicating that it's probably a problem with content script matching running too early (when iframe's location is still `about:blank`, i.e. before the `document.write`).

However, I ran into a bigger problem. I can't get `document.write` working on Firefox. It always results in a `DOMException: The operation is insecure.`

So that rules out the `document.write` approach.

Taking a step back, why does HyperChat need to in its own frame in the first place? Is it purely for CSS isolation? If so, there are alternative solutions for that. It would be better if HyperChat simply didn't use an iframe, due to their cross origin issues and overhead.

**Comment by KentoNishi** [comment]
reasoning is for postmessaging logic. youtube refuses to postmessage the timestamp of the video unless the domain of the iframe containing the chat is youtube.com. doing the hyperchat frame top-level prevents it from properly receiving the timestamp data when the user seeks the video.

**Comment by lbmaian** [comment]
I'm confused. The chat frame is already in the youtube.com domain. I'm questioning why HyperChat needs to be in a iframe rather than manipulating the original chat frame itself, doing away with the iframe completely.

**Comment by ChrRubin** [comment]
> I couldn't reproduce this on latest Chrome on Windows.

I've tried on Chromium 96.0.4664.45, Chrome 96.0.4664.45, and Edge 96.0.1054.41, all on Windows 10 20H2, all failing (as in not injecting into the iframe body) without errors in DevTools. And yeah as you mentioned on Firefox it fails with `DOMException: The operation is insecure.`

As for why HyperChat is in an iframe, for me its a no-headaches "it just works" solution, and there have been pretty minimal problems with it so far. If you can keep everything working while injecting HyperChat directly into YT chat without using an iframe (with minimal jank if possible), that's great. I tried to do that during the v2 rewrite and I just gave up since stuff weren't loading properly.

**Comment by KentoNishi** [comment]
Oh I thought you were talking about the layer of iframing used in embed mode surrounding the entirety of the chat. In regards to the inner iframe, yeah its basically an "if it ain't broke don't fix it" situation

**Comment by lbmaian** [comment]
Alright, I'll tinker with replacing the iframe with chatframe DOM manip. It looks like it's the only surefire way to avoid cross origin issues cross-browser. Plus, it should improve startup time and performance slightly in theory.

**Pull request closed without merging**
